"""
Django settings for cotizaciones_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-c1dwxtgvjgjh9400z-&^srx0ozb58d7tk-xjvsjxxx6fgqlp)8"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

_allowed_hosts_env = os.environ.get("ALLOWED_HOSTS")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_env.split(",") if host.strip()]
else:
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        ".railway.app",
        ".up.railway.app",
        ".ngrok-free.app",
        "070b-2806-103e-c-3f94-c4dd-15ca-650-5729.ngrok-free.app",
        "f82067d55692.ngrok-free.app",
        "8e4f3cd87ccf.ngrok-free.app",
        "f20c041eefef.ngrok-free.app",
        "6b73-187-195-124-21.ngrok-free.app",
    ]

_csrf_trusted_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS")
if _csrf_trusted_origins_env:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in _csrf_trusted_origins_env.split(",")
        if origin.strip()
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        "https://070b-2806-103e-c-3f94-c4dd-15ca-650-5729.ngrok-free.app",
        "https://f82067d55692.ngrok-free.app",
        "https://f20c041eefef.ngrok-free.app",
        "https://6b73-187-195-124-21.ngrok-free.app",
    ]
# Railway: añadir dominio público cuando esté disponible
_railway_domain = os.environ.get("RAILWAY_PUBLIC_DOMAIN")
if _railway_domain:
    CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + [f"https://{_railway_domain}"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'customers',
    'catalog',
    'accounts',
    'quotes.apps.QuotesConfig',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cotizaciones_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cotizaciones_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    # Railway y otros proveedores usan DATABASE_URL (postgres:// o postgresql://)
    _parsed = urlparse(_database_url)
    _db_name = _parsed.path.lstrip("/")
    if _parsed.scheme == "postgres":
        _parsed = _parsed._replace(scheme="postgresql")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _db_name,
            "USER": _parsed.username,
            "PASSWORD": _parsed.password,
            "HOST": _parsed.hostname,
            "PORT": _parsed.port or "5432",
            "OPTIONS": {"sslmode": "require"},
        }
    }
elif os.environ.get("POSTGRES_DB") or os.environ.get("PGDATABASE"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB") or os.environ.get("PGDATABASE"),
            "USER": os.environ.get("POSTGRES_USER") or os.environ.get("PGUSER", ""),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD") or os.environ.get("PGPASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST") or os.environ.get("PGHOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT") or os.environ.get("PGPORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es"

TIME_ZONE = "America/Mexico_City"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'quotes:dashboard'
LOGOUT_REDIRECT_URL = 'login'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# Motor del PDF de cotizaciones: "reportlab" (coordenadas en código) o "weasyprint" (template HTML)
QUOTE_PDF_ENGINE = os.environ.get("QUOTE_PDF_ENGINE", "reportlab")

# Datos de empresa para el PDF de cotizaciones (personalizables por entorno)
QUOTE_PDF_COMPANY = {
    "name": os.environ.get("QUOTE_PDF_COMPANY_NAME", "Sistemas de Conteo de Personas."),
    "website": os.environ.get("QUOTE_PDF_COMPANY_WEBSITE", "www.sisconper.com"),
    "street": os.environ.get(
        "QUOTE_PDF_COMPANY_STREET",
        "Blvd. Paseo de la República No. 13020 Int. 1307",
    ),
    "colony": os.environ.get("QUOTE_PDF_COMPANY_COLONY", "Col. Juriquilla, Querétaro, Qro."),
    "postal_code": os.environ.get("QUOTE_PDF_COMPANY_POSTAL_CODE", "C.P. 76230"),
    "phone": os.environ.get("QUOTE_PDF_COMPANY_PHONE", "(442) 245 7000"),
    "mobile": os.environ.get("QUOTE_PDF_COMPANY_MOBILE", ""),
    "rfc": os.environ.get("QUOTE_PDF_COMPANY_RFC", "SCP070410C43"),
    "email": os.environ.get("QUOTE_PDF_COMPANY_EMAIL", "info@sisconper.com"),
}
# Nombre para "Autorizado" en el PDF (Carlos Medina por defecto)
QUOTE_PDF_AUTHORIZED = os.environ.get("QUOTE_PDF_AUTHORIZED", "Carlos Medina")

# Pie de página del PDF (opcional)
QUOTE_PDF_PAYMENT_FORM = os.environ.get("QUOTE_PDF_PAYMENT_FORM", "")
QUOTE_PDF_DELIVERY_TIME = os.environ.get("QUOTE_PDF_DELIVERY_TIME", "")
QUOTE_PDF_WARRANTY = os.environ.get("QUOTE_PDF_WARRANTY", "")
QUOTE_PDF_DELIVERY_PLACE = os.environ.get("QUOTE_PDF_DELIVERY_PLACE", "")
