"""
Django settings for cotizaciones_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import warnings
from decimal import Decimal

# Suprimir aviso de dependencias de requests (urllib3/charset-normalizer)
warnings.filterwarnings("ignore", message=".*doesn't match a supported version.*", module="requests")
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En producción (DEBUG=False) SECRET_KEY es obligatorio.
_secret = os.environ.get("SECRET_KEY")
if not _secret and os.environ.get("DEBUG", "True") == "False":
    raise ValueError(
        "SECRET_KEY debe definirse en producción. "
        "Ej: export SECRET_KEY='$(python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\")'"
    )
SECRET_KEY = _secret or "django-insecure-dev-only-change-in-production"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

_allowed_hosts_env = os.environ.get("ALLOWED_HOSTS")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_env.split(",") if host.strip()]
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".railway.app", ".up.railway.app"]
# Railway: dominio público explícito (evitar ALLOWED_HOSTS=*)
_railway_public = os.environ.get("RAILWAY_PUBLIC_DOMAIN") or os.environ.get("RAILWAY_APP_DOMAIN")
if _railway_public:
    _host = _railway_public.strip().replace("https://", "").replace("http://", "").rstrip("/")
    if _host and _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)
# Contabo: dominio o IP (ej: cotizaciones.tudominio.com)
_contabo_domain = os.environ.get("CONTABO_DOMAIN")
if _contabo_domain:
    for d in _contabo_domain.split(","):
        d = d.strip()
        if d and d not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(d)
# Dev: ngrok u otros hosts vía NGROK_HOSTS (ej: abc123.ngrok-free.app)
_ngrok_hosts = os.environ.get("NGROK_HOSTS")
if _ngrok_hosts:
    for h in _ngrok_hosts.split(","):
        h = h.strip()
        if h and h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(h)

_csrf_trusted_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS")
if _csrf_trusted_origins_env:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in _csrf_trusted_origins_env.split(",")
        if origin.strip()
    ]
else:
    CSRF_TRUSTED_ORIGINS = []
# Railway: añadir dominio público (HTTP y HTTPS por si el proxy cambia el esquema)
_railway_domain = os.environ.get("RAILWAY_PUBLIC_DOMAIN") or os.environ.get("RAILWAY_APP_DOMAIN")
if _railway_domain:
    _domain = _railway_domain.strip().replace("https://", "").replace("http://", "").rstrip("/")
    for _scheme in ("https", "http"):
        _origin = f"{_scheme}://{_domain}"
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + [_origin]
# NGROK_HOSTS: orígenes HTTPS para ngrok (dev)
if _ngrok_hosts:
    for h in _ngrok_hosts.split(","):
        h = h.strip()
        if h:
            _origin = f"https://{h}" if not h.startswith("http") else h
            if _origin not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + [_origin]
# Contabo: añadir orígenes HTTPS para el dominio del servidor
if _contabo_domain:
    for d in _contabo_domain.split(","):
        d = d.strip()
        if d:
            _origin = f"https://{d}"
            if _origin not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + [_origin]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'django_filters',
    'customers',
    'catalog',
    'accounts',
    'quotes.apps.QuotesConfig',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cotizaciones_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cotizaciones_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    # Railway y otros proveedores usan DATABASE_URL (postgres:// o postgresql://)
    _parsed = urlparse(_database_url)
    _db_name = _parsed.path.lstrip("/")
    if _parsed.scheme == "postgres":
        _parsed = _parsed._replace(scheme="postgresql")
    # Contabo: si PostgreSQL está en localhost, usar sslmode=disable (o DATABASE_SSL_MODE)
    _db_host = (_parsed.hostname or "").lower()
    _ssl_mode = os.environ.get("DATABASE_SSL_MODE")
    if _ssl_mode is None and _db_host in ("localhost", "127.0.0.1", ""):
        _ssl_mode = "disable"
    elif _ssl_mode is None:
        _ssl_mode = "require"
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _db_name,
            "USER": _parsed.username,
            "PASSWORD": _parsed.password,
            "HOST": _parsed.hostname,
            "PORT": _parsed.port or "5432",
            "OPTIONS": {"sslmode": _ssl_mode},
        }
    }
elif os.environ.get("POSTGRES_DB") or os.environ.get("PGDATABASE"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB") or os.environ.get("PGDATABASE"),
            "USER": os.environ.get("POSTGRES_USER") or os.environ.get("PGUSER", ""),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD") or os.environ.get("PGPASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST") or os.environ.get("PGHOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT") or os.environ.get("PGPORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es"

TIME_ZONE = "America/Mexico_City"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'quotes:dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Cookies seguras para HTTPS (Railway sirve por HTTPS)
# Solo en producción (DEBUG=False) para que el login funcione correctamente
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Tipo de cambio por defecto (MXN por 1 USD) al elegir moneda MXN en nueva cotización (editable en el formulario)
QUOTE_DEFAULT_USD_MXN_RATE = Decimal(os.environ.get("QUOTE_DEFAULT_USD_MXN_RATE", "20.00"))

# Motor del PDF de cotizaciones: "reportlab" (coordenadas en código) o "weasyprint" (template HTML)
QUOTE_PDF_ENGINE = os.environ.get("QUOTE_PDF_ENGINE", "reportlab")
# Imagen del encabezado derecho (a la altura del logo). Ruta en static, ej: img/quote_header_right.png
QUOTE_PDF_HEADER_IMAGE = os.environ.get("QUOTE_PDF_HEADER_IMAGE", "img/quote_header_right.png")

# Datos de empresa para el PDF de cotizaciones (personalizables por entorno)
QUOTE_PDF_COMPANY = {
    "name": os.environ.get("QUOTE_PDF_COMPANY_NAME", "Sistemas de Conteo de Personas."),
    "website": os.environ.get("QUOTE_PDF_COMPANY_WEBSITE", "www.sisconper.com"),
    "street": os.environ.get(
        "QUOTE_PDF_COMPANY_STREET",
        "Blvd. Paseo de la República No. 13020 Int. 1307",
    ),
    "colony": os.environ.get("QUOTE_PDF_COMPANY_COLONY", "Col. Juriquilla, Querétaro, Qro."),
    "postal_code": os.environ.get("QUOTE_PDF_COMPANY_POSTAL_CODE", "C.P. 76230"),
    "phone": os.environ.get("QUOTE_PDF_COMPANY_PHONE", "(442) 245 7000"),
    "mobile": os.environ.get("QUOTE_PDF_COMPANY_MOBILE", ""),
    "rfc": os.environ.get("QUOTE_PDF_COMPANY_RFC", "SCP070410C43"),
    "email": os.environ.get("QUOTE_PDF_COMPANY_EMAIL", "info@sisconper.com"),
}
# Nombre para "Autorizado" en el PDF (Carlos Medina por defecto)
QUOTE_PDF_AUTHORIZED = os.environ.get("QUOTE_PDF_AUTHORIZED", "Carlos Medina")

# Pie de página del PDF (opcional)
QUOTE_PDF_PAYMENT_FORM = os.environ.get("QUOTE_PDF_PAYMENT_FORM", "")
QUOTE_PDF_DELIVERY_TIME = os.environ.get("QUOTE_PDF_DELIVERY_TIME", "")
QUOTE_PDF_WARRANTY = os.environ.get("QUOTE_PDF_WARRANTY", "")
QUOTE_PDF_DELIVERY_PLACE = os.environ.get("QUOTE_PDF_DELIVERY_PLACE", "")

# drf-spectacular (OpenAPI / Swagger)
SPECTACULAR_SETTINGS = {
    "TITLE": "Cotizaciones API",
    "DESCRIPTION": "API REST para integración con ERP/CRM. Cotizaciones, clientes y catálogo.",
    "VERSION": "1.0.0",
}
