# Generated by Django 4.2.29 on 2026-03-23 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('country_code', models.CharField(blank=True, default='MX', help_text='MX = cliente en México (cotización usual en pesos). Otro código (ej. US) sugiere cotización en USD.', max_length=2, verbose_name='País (ISO)')),
                ('rfc', models.CharField(blank=True, max_length=50, verbose_name='RFC')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('street_address', models.CharField(blank=True, max_length=255, verbose_name='Calle y No.')),
                ('neighborhood', models.CharField(blank=True, max_length=150, verbose_name='Colonia')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='C.P.')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Celular')),
                ('billing_address', models.TextField(blank=True, verbose_name='Dirección de facturación')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Dirección de envío')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Celular')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Puesto')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Es principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['full_name'],
            },
        ),
    ]
