# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercontact",
            name="mobile",
            field=models.CharField(blank=True, max_length=50, verbose_name="Celular"),
        ),
    ]
