# Generated by Django 4.2.29 on 2026-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model_code', models.CharField(max_length=100, unique=True, verbose_name='Código de modelo')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('datasheet_file', models.FileField(blank=True, null=True, upload_to='datasheets/', verbose_name='Ficha técnica')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio base')),
                ('currency', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='USD', help_text='El precio base del catálogo se maneja en USD; en cotizaciones MXN se convierte con el tipo de cambio de la cotización.', max_length=3, verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Modelo de cámara',
                'verbose_name_plural': 'Modelos de cámara',
                'ordering': ['model_code'],
            },
        ),
    ]
