# Generated by Django 4.2.29 on 2026-03-23 19:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('EXPIRED', 'Expirada')], default='DRAFT', max_length=20, verbose_name='Estatus')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de emisión')),
                ('valid_until', models.DateField(verbose_name='Vigencia')),
                ('currency', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], max_length=3, verbose_name='Moneda')),
                ('usd_mxn_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Obligatorio si la moneda es MXN. Los precios de lista del catálogo están en USD.', max_digits=12, null=True, verbose_name='Tipo de cambio (MXN por 1 USD)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('special_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento especial aplicado al total de productos (todos los clientes).', max_digits=5, verbose_name='Descuento especial (%)')),
                ('special_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Descuento especial (monto)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='IVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('poe', models.BooleanField(default=False, verbose_name='PoE')),
                ('poe_monto', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='PoE (monto)')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('terms', models.TextField(blank=True, default='Entrega 10-15 días hábiles. Pago 50% anticipo, 50% contra entrega. Garantía 1 año.', verbose_name='Términos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customers.customercontact', verbose_name='Contacto')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer', verbose_name='Cliente')),
                ('sales_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio unitario')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Descuento (monto)')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal línea')),
                ('configuration_notes', models.TextField(blank=True, verbose_name='Notas de configuración')),
                ('group_name', models.CharField(blank=True, help_text='Nombre del grupo (ej: Sistema de Conteo de Personas). Items con el mismo grupo se agrupan en la tabla.', max_length=120, verbose_name='Grupo')),
                ('order_in_group', models.PositiveSmallIntegerField(default=0, help_text='Orden dentro del grupo (0=primero).', verbose_name='Orden en grupo')),
                ('camera_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.cameramodel', verbose_name='Modelo de cámara')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Item de cotización',
                'verbose_name_plural': 'Items de cotización',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['sales_user', 'status'], name='quotes_quot_sales_u_eeb833_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['issue_date'], name='quotes_quot_issue_d_309cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer', 'status'], name='quotes_quot_custome_0a5a48_idx'),
        ),
    ]
