# Generated by Django 5.2.8 on 2026-02-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='group_name',
            field=models.CharField(blank=True, help_text='Nombre del grupo (ej: Sistema de Conteo de Personas). Items con el mismo grupo se agrupan en la tabla.', max_length=120, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='order_in_group',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden dentro del grupo (0=primero).', verbose_name='Orden en grupo'),
        ),
    ]
