# Generated by Django 5.2.8

from decimal import Decimal
from django.db import migrations, models


def backfill_discount_percent(apps, schema_editor):
    QuoteItem = apps.get_model("quotes", "QuoteItem")
    for item in QuoteItem.objects.all():
        line_before = (item.unit_price or Decimal("0")) * (item.quantity or 0)
        if line_before > 0 and item.discount_amount and item.discount_amount > 0:
            item.discount_percent = (item.discount_amount / line_before * 100).quantize(
                Decimal("0.01")
            )
            if item.discount_percent > 100:
                item.discount_percent = Decimal("100.00")
            item.save(update_fields=["discount_percent"])
        else:
            item.discount_percent = Decimal("0.00")
            item.save(update_fields=["discount_percent"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Descuento (%)",
            ),
            preserve_default=True,
        ),
        migrations.RunPython(backfill_discount_percent, noop),
        migrations.AlterField(
            model_name="quoteitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Descuento (monto)",
            ),
        ),
    ]
