# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_quoteitem_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="special_discount",
            field=models.BooleanField(
                default=False,
                help_text="Marcar cuando aplica el descuento especial para todos los clientes.",
                verbose_name="Descuento especial",
            ),
        ),
    ]
