# Generated by Django 5.2.8

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_quoteitem_special_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="special_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Porcentaje de descuento especial aplicado al total de productos (todos los clientes).",
                max_digits=5,
                verbose_name="Descuento especial (%)",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="special_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Descuento especial (monto)",
            ),
        ),
        migrations.RemoveField(
            model_name="quoteitem",
            name="special_discount",
        ),
    ]
