# Generated by Django 5.1.6 on 2026-02-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_add_quote_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quote',
            new_name='quotes_quot_sales_u_eeb833_idx',
            old_name='quotes_sales_status_idx',
        ),
        migrations.RenameIndex(
            model_name='quote',
            new_name='quotes_quot_issue_d_309cb1_idx',
            old_name='quotes_issue_date_idx',
        ),
        migrations.RenameIndex(
            model_name='quote',
            new_name='quotes_quot_custome_0a5a48_idx',
            old_name='quotes_customer_status_idx',
        ),
    ]
