# Generated by Django 5.2.8 on 2026-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_rename_quotes_sales_status_idx_quotes_quot_sales_u_eeb833_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='terms',
            field=models.TextField(blank=True, default='Entrega 10-15 días hábiles. Pago 50% anticipo, 50% contra entrega. Garantía 1 año.', verbose_name='Términos'),
        ),
    ]
