# Generated by Django 5.2.8

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_quote_special_discount_quoteitem_special_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="cableado",
            field=models.BooleanField(default=False, verbose_name="Cableado"),
        ),
        migrations.AddField(
            model_name="quote",
            name="cableado_monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Cableado (monto)",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="instalacion",
            field=models.BooleanField(default=False, verbose_name="Instalación"),
        ),
        migrations.AddField(
            model_name="quote",
            name="instalacion_monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Instalación (monto)",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="inyector_poe",
            field=models.BooleanField(default=False, verbose_name="Inyector PoE"),
        ),
        migrations.AddField(
            model_name="quote",
            name="inyector_poe_monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Inyector PoE (monto)",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="poe",
            field=models.BooleanField(default=False, verbose_name="PoE"),
        ),
        migrations.AddField(
            model_name="quote",
            name="poe_monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="PoE (monto)",
            ),
        ),
    ]
